version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vacantes_BBDD_2024_EXA
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - backend

  backend:
    build: ./backend
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - backend

networks:
  backend: